### ISSUE TITLE
Appium Dashboard has no Sessions in Hub + Node setup of Device Farm

### ISSUE THREAD

**Issue by ValzRon** [sudharsan-selvaraj/appium-dashboard-plugin#128]
Hello,

i've noticed that the Appium Dashboard remains empty when I run sessions with a hub + node configuration of device farm.
Currently im running device farm with one hub and 8 nodes in a Kubernetes cluster. 
It uses ConfigMap to dynamicly apply the hub/node config. **This is for the hub:**
```
apiVersion: v1
data:
  appium-config.yaml: |
    server:
      relaxed-security: true
      base-path: /wd/hub
      keep-alive-timeout: 800
      port: 4723
      use-plugins:
        - device-farm
        - appium-dashboard
      plugin:
        device-farm:
          platform: android
kind: ConfigMap
metadata:
  name: device-farm-hub-cm
  namespace: default
```
**and this is for the node:**
```
apiVersion: v1
data:
  appium-config.yaml: |
    server:
      relaxed-security: true
      base-path: /wd/hub
      keep-alive-timeout: 800
      port: 4723
      use-plugins:
        - device-farm
        - appium-dashboard
      plugin:
        device-farm:
          platform: android
          hub: http://device-farm-hub.default.svc.cluster.local:4723
kind: ConfigMap
metadata:
  name: device-farm-node-cm
  namespace: default
```
This works just fine. I also configured that the service is reachable via port 31337 not 4723, so I can lookup -->
"my.domain.com:31337/device-farm/" and "my.domain.com:31337/dashboard/".

Im using:
Appium beta.64
Appium Dashboard 2.02
Device-Farm 7.2
The 8 nodes all have an Android Emulator with API23 (so fairly old) and Espresso 2.15.0

Does Dashboard even work in this kind of setup? Has it been tested for remote execution?
I can provide additional logs if necessary.
